# Generated by Django 3.2.3 on 2021-05-20 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(default=datetime.datetime(2021, 5, 21, 15, 26, 27, 220940))),
                ('task_text', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
